# Generated by Django 3.2.14 on 2022-08-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creater_date',
            new_name='created_date',
        ),
    ]
